### ISSUE TITLE
Class names concatenation

### ISSUE THREAD

**Issue by goliney** [jareware/css-architecture#16]
Some people (like myself) may find it incredibly difficult to search for styles when concatenation is done like this:
```css
.myapp-Header {
  background: black;
  color: white;

  &-link {
    color: blue;
  }

  &-signup {
    border: 1px solid gray;
  }
}
```
Isn't it better to be able to just grab a style from the dev tools and search for it directly?
